name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: deploy
        with:
          path: src
          default-version: main
      - run: |
        ls ${{ steps.deploy.outputs.outputDirectory }}
        cat ${{ steps.deploy.outputs.outputDirectory }}/index.html
        cat ${{ steps.deploy.outputs.outputDirectory }}/versions.json
